services:
  letters-anonymous-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: letters-anonymous-web
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "127.0.0.1:3003:80"
    volumes:
      - ./.env.production:/var/www/html/.env:ro
      - ./writable:/var/www/html/writable
      - ./public/uploads:/var/www/html/public/uploads
